version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - gdata:/var/lib/postgresql/data
volumes:
  gdata: